services:
  _defaults:
    autowire: true
    autoconfigure: true

  # DataFixtures for test environment
  WechatMiniProgramStatsBundle\DataFixtures\:
    resource: '../../DataFixtures/'
    tags: ['doctrine.fixture.orm']